### ISSUE TITLE
Is it useful in Windows ?

### ISSUE THREAD

**Issue by jocker-il** [narc0tiq/factorio-mod-makefile#2]
Is it usable in Windows or can it be amended/  extended to be used in Windows ?

I know things like sed have Windows variants - so that's one thing less to worry about,

BR,
JoCKeR

**Comment by narc0tiq** [comment]
It's technically possible, but you'd need to provide `cat`, `git`, `find`, `sed`, `luac`, and a Linux-compatible `mkdir`; probably the easiest way to do this would be to install something like [MSYS2][msys2] -- at which point, you're technically not running the Makefile in Windows anyway.

[Lua for Windows][lua4w] appears to have fallen behind by about 4 years or more, otherwise I'd suggest installing that and using it with the Git Bash shell (an MSYS2 environment).

[msys2]: https://www.msys2.org/
[lua4w]: https://github.com/rjpcomputing/luaforwindows
